# 记载程序对应的文件

[editorconfig]
editorconfig = "editorconfig.ini"
origin = ".editorconfig"

[llvm]
clang-format = "clang-format.yaml"
origin = ".clang-format"

[pinyin]
pinyin = "pinyin.txt"

[rust.clang-format]
clang-format = "rust.clang-format"
origin = ".clang-format"

[vscode.settings.clangd]
clangd = "clangd.jsonc"

[vscode.settings]
settings = "settings.json"

[xmake]
xmake = "xmake.lua"
origin = "xmake.lua"
